/// Flutter icons Togas
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Togas
///      fonts:
///       - asset: fonts/Togas.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Togas {
  Togas._();

  static const _kFontFam = 'Togas';
  static const String? _kFontPkg = null;

  static const IconData togas = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
